# Generated by Django 5.0.6 on 2024-11-23 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_booking_owner_delete_turf_booking_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="owner",
            new_name="owner_turf_id",
        ),
        migrations.RenameField(
            model_name="owner",
            old_name="uuid",
            new_name="turf_id",
        ),
    ]
